# -*- coding: utf-8 -*-
"""Linear_Regression_Hiring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19hPjj7n011szt4rC4nIzde00CnIokEiI

The csv file contains hiring stats for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, I have build a machine learning model for HR department that can help them decide salaries for future candidates. Using this, I have predicted salaries for following candidates,

2 yr experience, 9 test score, 6 interview score
12 yr experience, 10 test score, 10 interview score
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

!pip install word2number
from word2number import w2n

df = pd.read_csv('/content/hiring.csv')

df

df['test_score'].median()

df['test_score'].fillna(8, inplace = True)

df

# Converting the 'experience' column to string type before applying the function
df['experience'] = df['experience'].astype(str)
# Replacing non-number words (like NaN) with a default value (e.g., 'zero')
df['experience'] = df['experience'].str.lower().replace(['nan', ''], 'zero', regex=True)
df['experience'] = df['experience'].apply(w2n.word_to_num)

df

"""**Replacing '0' with '1'**"""

df = df.replace(to_replace=0, value = 1)

df

"""**Building Linear Regression Model**"""

reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

reg.coef_

reg.intercept_

"""**Predicting Salary of a candidate having 2 yr experience, 9 test score, 6 interview**"""

print(reg.predict([[2,9,6]]))

"""**Prediction of Salary of 12 yr experience, 10 test score, 10 interview score**"""

print(reg.predict([[12,10,10]]))